services:
    wsse.security.authentication.provider:
        class: SD\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
        public: false

    wsse.security.authentication.listener:
        class: SD\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]
        public: false