node:
  build: ./docker/node
  volumes:
  - ./server:/usr/src/app
  - ./docker/node/run.sh:/usr/src/run.sh
  links:
  - mongodb:mongodb
  ports:
  - 8181:8181
  command: bash /usr/src/run.sh
  container_name: Akaunto_node

mongodb:
  image: mongo:2.6.12
  volumes:
  - ./docker/db:/data/db
  container_name: Akaunto_mongodb

# Administration interface for MongoDB, accessible on http://localhost:5678/
genghis:
  image: dockervan/genghis
  links:
  - mongodb:db
  ports:
  - 5678:5678

# Container to run server-side tests
test:
  build: ./docker/node
  volumes:
  - ./server:/usr/src/app
  - ./docker/node/test.sh:/usr/src/test.sh
  links:
  - mongodb:mongodb
  command: bash /usr/src/test.sh
  container_name: Akaunto_test
