<?php

namespace SD\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    /**
     * Returns the salt of the specified user.
     *
     * @param string $username
     * @return string|null
     * @throws NoResultException
     */
    public function getSaltByUsername($username) {
        $query = $this->_em->createQuery("SELECT u.salt FROM SDUserBundle:User u WHERE u.username = :username");
        $query->setParameters(["username" => $username]);
        return $query->getSingleScalarResult();
    }
}
