<?php

namespace SD\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepositor
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository {

    /**
     * Returns all the accounts associated to the specified user.
     *
     * @param User $user
     * @return Account[]
     */
    public function findAccountsForUserId($user) {
        $query = $this->_em->createQuery("SELECT a, au FROM SDAppBundle:Account a JOIN a.associatedUsers au WHERE au.user = :id");
        $query->setParameters(["id" => $user->getId()]);
        return $query->getResult();
    }
}
