sd_app:
    resource: "@SDAppBundle/Resources/config/routing.yml"
    prefix:   /

sd_user:
    resource: "@SDUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST
rest:
    type: rest
    resource: "routing_rest.yml"
    prefix: /api