root: true
extends: "fingerproof/es6"
rules:
    indent: [2, 4]
    func-names: 0
    no-param-reassign: [2, {"props": false}]
    max-len: [1, 160, 4]
globals:
    sessionStorage: true
    document: true
