root: true
extends: "fingerproof/es6"
rules:
    indent: [2, 4]
    id-length: [2, {"min": 1}]
    func-names: 0
    no-param-reassign: [2, {"props": false}]
    max-len: [1, 160, 4]
    max-params: [2, 16]
    brace-style: [2, "1tbs"]
globals:
    sessionStorage: true
    document: true
